### ISSUE TITLE
  need references

### ISSUE THREAD

**Issue by timm** [ai-se/NSF-19-Fairness-FAI#2]
Need like ten references for this sentence:

  Machine learning models are used to support decision making in high-stakes applications such as mortgage lending, hiring, and prison sentencing. Many high-stake applications such as finance, hiring, admissions, criminal justice use algorithmic decision-making frequently

please add the appropriate citations to proposal.bib

**Comment by Suvodeep90** [comment]
@article{ladd1998evidence,
  title={Evidence on discrimination in mortgage lending},
  author={Ladd, Helen F},
  journal={Journal of Economic Perspectives},
  volume={12},
  number={2},
  pages={41--62},
  year={1998}
}

@article{burrell2016machine,
  title={How the machine ‘thinks’: Understanding opacity in machine learning algorithms},
  author={Burrell, Jenna},
  journal={Big Data \& Society},
  volume={3},
  number={1},
  pages={2053951715622512},
  year={2016},
  publisher={SAGE Publications Sage UK: London, England}
}

@article{corbett2018measure,
  title={The measure and mismeasure of fairness: A critical review of fair machine learning},
  author={Corbett-Davies, Sam and Goel, Sharad},
  journal={arXiv preprint arXiv:1808.00023},
  year={2018}
}

@article{galindo2000credit,
  title={Credit risk assessment using statistical and machine learning: basic methodology and risk modeling applications},
  author={Galindo, Jorge and Tamayo, Pablo},
  journal={Computational Economics},
  volume={15},
  number={1-2},
  pages={107--143},
  year={2000},
  publisher={Springer}
}

@misc{yan2013system,
  title={System and method of detecting and assessing multiple types of risks related to mortgage lending},
  author={Yan, Rui and Chi, Hoi-Ming and Koo, Seongjoon and Baker, James},
  year={2013},
  month=jul # "~16",
  publisher={Google Patents},
  note={US Patent 8,489,499}
}

@article{chalfin2016productivity,
  title={Productivity and selection of human capital with machine learning},
  author={Chalfin, Aaron and Danieli, Oren and Hillis, Andrew and Jelveh, Zubin and Luca, Michael and Ludwig, Jens and Mullainathan, Sendhil},
  journal={American Economic Review},
  volume={106},
  number={5},
  pages={124--27},
  year={2016}
}

@article{ajit2016prediction,
  title={Prediction of employee turnover in organizations using machine learning algorithms},
  author={Ajit, Pankaj},
  journal={algorithms},
  volume={4},
  number={5},
  pages={C5},
  year={2016}
}

@article{berk2015machine,
  title={Machine learning forecasts of risk to inform sentencing decisions},
  author={Berk, Richard and Hyatt, Jordan},
  journal={Federal Sentencing Reporter},
  volume={27},
  number={4},
  pages={222--228},
  year={2015},
  publisher={JSTOR}
}

@phdthesis{ozkan2017predicting,
  title={Predicting recidivism through machine learning},
  author={Ozkan, Turgut},
  year={2017}
}

@article{berk2016forecasting,
  title={Forecasting domestic violence: A machine learning approach to help inform arraignment decisions},
  author={Berk, Richard A and Sorenson, Susan B and Barnes, Geoffrey},
  journal={Journal of Empirical Legal Studies},
  volume={13},
  number={1},
  pages={94--115},
  year={2016},
  publisher={Wiley Online Library}

**Comment by Suvodeep90** [comment]
added to the ref to .bib file
