### ISSUE TITLE
please make a latex table

### ISSUE THREAD

**Issue by timm** [ai-se/NSF-19-Fairness-FAI#3]
![image](https://user-images.githubusercontent.com/29195/59570090-bdf94180-9060-11e9-9ab4-8ba3f97f8e75.png)

ignore column2 and al the rows that say "overlap". and ignore all the percentages.

**Comment by Suvodeep90** [comment]
\begin{table}[]
\begin{tabular}{llll}
\hline
Group                 & AWS & ModelDepot & Wolfarm \\ \hline
Image                 & 61  & 24         & 59      \\ \hline
Video                 & 13  & 2          & 0       \\ \hline
Natural Langage texts & 35  & 5          & 18      \\ \hline
Audio                 & 12  & 1          & 2       \\ \hline
Strctured             & 107 & 0          & 0       \\ \hline
Total                 & 228 & 3          & 79      \\ \hline
\end{tabular}
\end{table}
